version: '3'
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - ./data:/var/lib/postgresql/data
  spark-master:
    image: bitnami/spark
    ports:
      - 8080:8080
    depends_on:
      - postgres
  spark-worker1:
    image: bitnami/spark
    depends_on:
      - spark-master
  spark-worker2:
    image: bitnami/spark
    depends_on:
      - spark-master
