version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - ./data:/var/lib/postgresql/data
  spark-master:
    image: spark
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
    depends_on:
      - postgres
  spark-worker1:
    image: spark
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
    depends_on:
      - spark-master
  spark-worker2:
    image: spark
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
    depends_on:
      - spark-master
